version: "3"

services:
  server:
    build: .
    ports: 
      - 50051:50051
    container_name: server
    command: bash -c "go run server/server.go"
    depends_on:
      - mysql
    volumes:
      - ./api:/app/api
