version: "3"

services:
  server:
    build: .
    ports: 
      - 50051:50051
    container_name: server
    command: bash -c "go run server/server.go"
    depends_on:
      - mysql
    volumes:
      - ./api:/app/api
  
  client:
    build: .
    ports:
      - 8080:8080
    container_name: client
    command: bash -c "go run client/client.go"
    depends_on:
      - server
    volumes:
      - ./api:/app/api
  
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go_database
      MYSQL_USER: go_grpc
      MYSQL_PASSWORD: password
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.conf

  frontend:
    build: ./front
    ports:
      - 3000:3000
    container_name: frontend
    environment:
      - NODE_ENV=development
    volumes:
      - ./front/:/usr/src/app
    command: sh -c 'yarn start'
    depends_on:
      - client
